import type { Service, Destination, Testimonial, LanguageClass, Milestone, BlogPost, Scholarship } from '@/types';


export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'Services', href: '/services' },
  { label: 'Destinations', href: '/destinations' },
  { label: 'About', href: '/about' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contact', href: '/contact' },
];

export const SERVICES: Service[] = [
  {
    id: '1',
    title: 'Education Counseling',
    slug: 'education-counseling',
    icon: 'globe',
    description: 'Expert guidance on choosing the right university and course tailored to your career goals in Japan, Korea, Australia, and more.',
    fullDescription: 'Choosing the right career path is confusing. Our certified counselors analyze your profile, interests, and financial plan to recommend the best universities and courses.',
    points: ['Profile Analysis', 'University Shortlisting', 'Career Mapping'],
    methodology: "Our counseling approach is student-centric. We use a proprietary 3-step verification process to ensure every recommendation aligns with current global market trends and the student's long-term aspirations.",
    detailedProcess: [
      { title: 'In-depth Profile Analysis', desc: 'We review your academic history, language proficiency, and financial background.' },
      { title: 'Goal Alignment', desc: 'Matching your interests with career-driven courses and top-tier institutions.' },
      { title: 'University Comparison', desc: 'Evaluating universities based on ranking, tuition, location, and post-study opportunities.' },
    ],
    credentials: ['Ministry of Social Development (MoSD) Approved', 'CTEVT TITI Trained Counselors', 'British Council Certified Experts'],
   team: [
      { name: 'Shreya Poudyal', slug: 'shreya-poudyal', role: 'Chief Counselor', credentials: ['CTEVT TITI Certified', 'MSc. Microbiology St. Xavier College (Tribhuvan University)'],
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200' },
      { name: 'Yusha Hada', slug: 'yusha-hada', role: 'Senior Counselor', credentials: ['TEVT TITI Certified', 'Bachelor in Hotel Management (Tribhuvan University)'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
      {
        name: 'Alisha Adhikari ', slug: 'alisha-adhikari', role: 'Center Manager', credentials: ['British Council Certified', 'Bachelor in Business Administration & Master in Sociology (Tribhuvan University)',
          'Miss Nepal 2018 Finalist', 'Former Cabin Crew (Airhostess) at Shree Airlines'],
        image: 'https://i.pravatar.cc/150?u=anju'
      },
        { name: 'Sanju Panthi', slug: 'sanju-panthi', role: 'Documentation Officer', credentials: ['British Council Certified', 'Master in Business Administration Tribhuvan University'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
    ],
  },
  {
    id: '2',
    title: 'Scholarship Guidance',
    slug: 'scholarship-guidance',
    icon: 'award',
    description: 'Dedicated support to help you identify and apply for merit-based and need-based scholarships globally.',
    fullDescription: "Education shouldn't be a burden. We help you identify and apply for merit-based, government, and university-specific scholarships.",
    points: ['Merit Scholarships', 'Need-based Aid', 'Application Review'],
    methodology: 'We maintain a direct database of internal university scholarships not always advertised to the public. We guide students on crafting compelling essays and SOPs that maximize funding potential.',
    detailedProcess: [
      { title: 'Scholarship Mapping', desc: 'Identifying fully-funded and partial scholarships for your profile.' },
      { title: 'Essay Mentoring', desc: 'Professional guidance on scholarship-specific personal statements.' },
      { title: 'Interview Coaching', desc: 'Preparing for merit-based scholarship interviews with mock sessions.' },
    ],
    credentials: ['Authorized University Representatives', 'MoSD Approved Documentation Process'],
  team: [
      { name: 'Shreya Poudyal', slug: 'shreya-poudyal', role: 'Chief Counselor', credentials: ['CTEVT TITI Certified', 'MSc. Microbiology St. Xavier College (Tribhuvan University)'],
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200' },
      { name: 'Yusha Hada', slug: 'yusha-hada', role: 'Senior Counselor', credentials: ['TEVT TITI Certified', 'Bachelor in Hotel Management (Tribhuvan University)'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
      {
        name: 'Alisha Adhikari ', slug: 'alisha-adhikari', role: 'Career Strategist', credentials: ['British Council Certified', 'Bachelor in Business Administration & Master in Sociology (Tribhuvan University)',
          'Miss Nepal 2018 Finalist', 'Former Cabin Crew (Airhostess) at Shree Airlines'],
        image: 'https://i.pravatar.cc/150?u=anju'
      },
        { name: 'Sanju Panthi', slug: 'sanju-panthi', role: 'Senior Counselor', credentials: ['British Council Certified', 'Master in Business Administration Tribhuvan University'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
    ],
  },
  {
    id: '3',
    title: 'Test Preparation',
    icon: 'book-open',
    slug: 'test-preparation',
    description: 'Comprehensive preparation classes for IELTS, PTE, JLPT, NAT, and TOPIK with experienced instructors and mock tests.',
    fullDescription: 'Get the scores you need. We offer intensive preparation classes for IELTS, PTE, JLPT, and TOPIK with experienced instructors and weekly mock tests.',
    points: ['Free Mock Tests', 'Updated Materials', 'Flexible Timing'],
    methodology: 'Interactive classroom sessions combined with digital lab practice. We focus on weakness-spotting and time management strategies through weekly full-length mock exams.',
    detailedProcess: [
      { title: 'Diagnostic Testing', desc: 'Initial test to determine your baseline and target areas.' },
      { title: 'Intensive Training', desc: 'Daily sessions covering Reading, Writing, Listening, and Speaking.' },
      { title: 'Feedback Loops', desc: 'Detailed individual feedback after every mock test.' },
    ],
    credentials: ['British Council Certified Instructors', 'Official PTE Lab Facilities', 'Japanese/Korean Native Trained Staff'],
    team: [
      { name: 'Shreya Poudyal', slug: 'shreya-poudyal', role: 'Chief Counselor', credentials: ['CTEVT TITI Certified', 'MSc. Microbiology St. Xavier College (Tribhuvan University)'],
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200' },
      { name: 'Yusha Hada', slug: 'yusha-hada', role: 'Senior Counselor', credentials: ['TEVT TITI Certified', 'Bachelor in Hotel Management (Tribhuvan University)'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
      {
        name: 'Alisha Adhikari ', slug: 'alisha-adhikari', role: 'Career Strategist', credentials: ['British Council Certified', 'Bachelor in Business Administration & Master in Sociology (Tribhuvan University)',
          'Miss Nepal 2018 Finalist', 'Former Cabin Crew (Airhostess) at Shree Airlines'],
        image: 'https://i.pravatar.cc/150?u=anju'
      },
        { name: 'Sanju Panthi', slug: 'sanju-panthi', role: 'Senior Counselor', credentials: ['British Council Certified', 'Master in Business Administration Tribhuvan University'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
    ],
  },
  {
    id: '4',
    title: 'Visa Documentation',
    slug: 'visa-documentation',
    icon: 'file-check',
    description: 'Meticulous assistance with visa applications, financial documentation, and interview preparation to ensure high success rates.',
    fullDescription: 'One small mistake can lead to visa rejection. We meticulously guide you through financial documents, SOP writing, and form filling to ensure a 98% success rate.',
    points: ['Financial Guidance', 'SOP Assistance', 'Mock Interviews'],
    methodology: 'Double-tier verification of all documentation. We simulate the actual embassy interview environment multiple times until the student is confident and clear.',
    detailedProcess: [
      { title: 'Visa Checklist', desc: 'Systematic gathering of academic, financial, and legal papers.' },
      { title: 'SOP Refinement', desc: 'Turning your story into a professional and persuasive statement.' },
      { title: 'Final Review', desc: 'MoSD-approved standards check before submission.' },
    ],
    credentials: ['Ministry of Social Development', 'Certified Documentation Experts'],
     team: [
      { name: 'Shreya Poudyal', slug: 'shreya-poudyal', role: 'Chief Counselor', credentials: ['CTEVT TITI Certified', 'MSc. Microbiology St. Xavier College (Tribhuvan University)'],
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200' },
      { name: 'Yusha Hada', slug: 'yusha-hada', role: 'Senior Counselor', credentials: ['TEVT TITI Certified', 'Bachelor in Hotel Management (Tribhuvan University)'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
      {
        name: 'Alisha Adhikari ', slug: 'alisha-adhikari', role: 'Career Strategist', credentials: ['British Council Certified', 'Bachelor in Business Administration & Master in Sociology (Tribhuvan University)',
          'Miss Nepal 2018 Finalist', 'Former Cabin Crew (Airhostess) at Shree Airlines'],
        image: 'https://i.pravatar.cc/150?u=anju'
      },
        { name: 'Sanju Panthi', slug: 'sanju-panthi', role: 'Senior Counselor', credentials: ['British Council Certified', 'Master in Business Administration Tribhuvan University'],
        image: 'https://i.pravatar.cc/150?u=bishal' },
    ],
  },
  {
    id: '5',
    title: 'Student Accommodation',
    slug: 'student-accommodation',
    icon: 'home',
    description: 'Assistance in finding safe and affordable accommodation near your university.',
    fullDescription: "We don't just leave you at the airport. We assist in finding safe and affordable accommodation near your university before you even fly.",
    points: ['Dormitory Booking', 'Shared Apartments', 'Homestays'],
    methodology: 'Partnering with global housing providers like Casita and University Living to offer students vetted, safe, and student-friendly living options.',
    detailedProcess: [
      { title: 'Budget Planning', desc: 'Finding options that fit your monthly living allowance.' },
      { title: 'Vetting Process', desc: 'Ensuring security and proximity to campus.' },
      { title: 'Booking Support', desc: 'Handling contracts and deposit transfers safely.' },
    ],
    credentials: ['Global Housing Partnership Network'],
  },
  {
    id: '6',
    title: 'Health Insurance',
    slug: 'health-insurance',
    icon: 'heart',
    description: 'Help choosing the best and most affordable student health insurance plans.',
    fullDescription: 'Mandatory for most countries, we help you choose the best and most affordable student health insurance plans (OSHC, etc.).',
    points: ['OSHC (Australia)', 'IHS (UK)', 'Travel Insurance'],
    methodology: 'Comparison of all major health providers to find plans that offer maximum coverage for pre-existing conditions and mental health support.',
    detailedProcess: [
      { title: 'Requirement Check', desc: 'Confirming mandatory insurance levels for your specific visa.' },
      { title: 'Quote Comparison', desc: 'Finding the most affordable premium with high coverage.' },
      { title: 'Policy Issue', desc: 'Instant certificate generation for visa application.' },
    ],
    credentials: ['Authorized Insurance Agent Partnerships'],
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: 'au',
    country: 'Australia',
    count: 12,
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=800&auto=format&fit=crop',
    highlight: 'World-class education & lifestyle.',
    features: ['Post-Study Work Visa (2-4 yrs)', 'High Minimum Wage', 'PR Pathways Available', 'Part-time Work (48hrs/fn)', 'Scholarships for Merit'],
    details: {
      overview: 'Australia is the third most popular destination for international students. It boasts world-renowned universities, a high standard of living, and an incredibly diverse environment. The Australian education system is heavily regulated by the government to maintain high standards (ESOS Act), ensuring students receive quality education.',
      whyStudy: [
        'Globally Recognized Degrees (Group of Eight)',
        'Dynamic Post-Study Work Stream (Subclass 485)',
        'High Minimum Wage for Part-time Workers',
        'Safe, Multicultural Cities like Sydney and Melbourne',
        'Focus on Practical and Research-based Learning',
      ],
      intakes: ['February (Major Intake)', 'July (Secondary Intake)', 'November (Fast-track/Limited courses)'],
      costs: {
        tuition: 'AUD 20,000 - 45,000 per year (Bachelor/Master)',
        living: 'AUD 24,505 per year (As per Department of Home Affairs)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.0+), PTE (50+), or TOEFL',
        'Statement of Purpose (GTE/Genuine Student Requirement)',
        'Financial Stability Evidence (3 months bank balance)',
        'OSHC (Overseas Student Health Cover)',
      ],
      workRights: 'International students are permitted to work 48 hours per fortnight during sessions and unlimited hours during vacations.',
      popularCourses: [
        'Information Technology & Data Science',
        'Engineering (Civil, Electrical, Mechanical)',
        'Nursing & Health Sciences',
        'Accounting & Professional Year',
        'Tourism & Hospitality Management',
        'Business & MBA',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates (SLC to Bachelor)',
        'IELTS / PTE / TOEFL Score Report',
        'Letter of Recommendations (Min 2)',
        'Resume / CV (Updated)',
        'Work Experience Letter (If applicable)',
        'Personal Statement (SOP)',
      ],
      visaChecklist: [
        'COE (Confirmation of Enrollment)',
        'CAAW (If under 18)',
        'Financial Evidence (Bank Balance or Education Loan)',
        'Relationship Proof Documents',
        'Property Valuation & Income Sources',
        'Police Clearance Certificate',
        'OSHC Payment Receipt',
        'Visa Application Fee Payment',
      ],
      faqs: [
        { question: 'What is GTE in Australia?', answer: 'GTE stands for Genuine Temporary Entrant. It is an integrity assessment that every international student must pass to prove that they genuinely intend to stay in Australia temporarily for the purpose of study.' },
        { question: 'Can I take my spouse to Australia?', answer: 'Yes, Australia allows international students to bring their dependent family members (spouse and children) as secondary applicants on their student visa.' },
        { question: 'Is the Post-Study Work (PSW) visa still available?', answer: 'Yes, graduates of Australian institutions are eligible for the Temporary Graduate Visa (subclass 485), which allows them to live and work in Australia for 2 to 4 years depending on their level of study.' },
        { question: "What is the English score requirement for a Bachelor's degree?", answer: 'Generally, an IELTS score of 6.0 with no band less than 5.5, or a PTE score of 50 with no score less than 42, is required for most undergraduate programs.' },
      ],
    },
  },
  {
    id: 'ca',
    country: 'Canada',
    count: 14,
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=800&auto=format&fit=crop',
    highlight: 'Welcoming diverse society.',
    features: ['PGWP up to 3 Years', 'PR Friendly Policies', 'High Quality of Life', 'Co-op Programs', 'Work while studying'],
    details: {
      overview: 'Canada is one of the most immigrant-friendly countries in the world and consistently ranks among the top destinations for international students. With globally recognized universities, a safe multicultural environment, and clear pathways to permanent residency, Canada offers both an excellent education and a bright future.',
      whyStudy: [
        'Post-Graduation Work Permit (PGWP) up to 3 Years',
        'Clear PR Pathways via Express Entry and PNP',
        'World-Class Universities like UofT, UBC, and McGill',
        'Bilingual Country (English & French) – Expanded Opportunities',
        'Co-op and Internship Programs Integrated into Degrees',
      ],
      intakes: ['January (Winter Intake)', 'September (Major/Fall Intake)', 'May (Summer Intake – Limited)'],
      costs: {
        tuition: 'CAD 15,000 - 35,000 per year (Bachelor/Master)',
        living: 'CAD 15,000 - 20,000 per year depending on city',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.0+) or PTE (58+)',
        'Statement of Purpose (SOP)',
        'Proof of Financial Funds (CAD 10,000+ beyond first year tuition)',
        'Letter of Acceptance from a DLI (Designated Learning Institution)',
      ],
      workRights: 'International students can work up to 20 hours per week during academic sessions and full-time during scheduled breaks. Spouses may be eligible for an open work permit.',
      popularCourses: [
        'Computer Science & Artificial Intelligence',
        'Business Administration & MBA',
        'Engineering (Software, Mechanical, Civil)',
        'Health Sciences & Nursing',
        'Finance & Accounting',
        'Environmental Studies',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / PTE Score Report',
        'Statement of Purpose (SOP)',
        'Letter of Recommendation (Min 2)',
        'Resume / CV',
        'Work Experience Letter (If applicable)',
      ],
      visaChecklist: [
        'Letter of Acceptance from DLI',
        'Proof of Financial Support (Bank Statement / Loan Letter)',
        'Biometrics Enrollment',
        'Medical Examination (If required)',
        'Police Clearance Certificate',
        'Passport-sized Photos',
        'Visa Application Fee Payment',
        'Family Information Form (IMM 5645)',
      ],
      faqs: [
        { question: 'What is a PGWP?', answer: 'The Post-Graduation Work Permit (PGWP) allows international graduates of eligible Canadian institutions to work in Canada for a period equal to the length of their study program, up to a maximum of 3 years.' },
        { question: 'Can I apply for PR after studying in Canada?', answer: 'Yes. Canadian study experience qualifies you for PR pathways such as the Canadian Experience Class (CEC) under Express Entry, or through various Provincial Nominee Programs (PNP).' },
        { question: 'Can my spouse work in Canada on my student visa?', answer: 'Spouses of international students enrolled in eligible full-time programs at designated institutions may be eligible for an open work permit allowing them to work anywhere in Canada.' },
        { question: 'What is a DLI?', answer: 'A Designated Learning Institution (DLI) is a school approved by a provincial or territorial government to host international students. Only acceptance letters from DLIs are valid for a Canadian student visa application.' },
      ],
    },
  },
  {
    id: 'cy',
    country: 'Cyprus',
    count: 6,
    image: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?q=80&w=800&auto=format&fit=crop',
    highlight: 'Affordable European education.',
    features: ['Low Tuition Fees', 'No IELTS Required Options', 'Schengen Access (Ease)', 'Pleasant Climate', 'Work Rights Available'],
    details: {
      overview: 'Cyprus is an emerging destination for international students seeking affordable, quality European education. As an EU member state with English as a widely spoken language, Cyprus offers a unique blend of European academic standards and Mediterranean lifestyle at a fraction of the cost of Western Europe.',
      whyStudy: [
        'Affordable Tuition Compared to Western Europe',
        'English-Medium Programs Widely Available',
        'Safe and Welcoming Country for International Students',
        'EU-Recognized Degrees Open Doors Across Europe',
        'Pleasant Mediterranean Climate Year-Round',
      ],
      intakes: ['September/October (Major Intake)', 'February/March (Secondary Intake)'],
      costs: {
        tuition: 'EUR 4,000 - 10,000 per year (Bachelor/Master)',
        living: 'EUR 700 - 1,000 per month',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (5.5+) or equivalent (some programs waive this)',
        'Statement of Purpose',
        'Proof of Financial Means',
        'Acceptance Letter from a Recognized Cyprus University',
      ],
      workRights: 'International students from non-EU countries are permitted to work up to 20 hours per week during the academic year and full-time during official university breaks.',
      popularCourses: [
        'Business Administration & Management',
        'Hotel & Tourism Management',
        'Computer Science & IT',
        'Law',
        'Media & Communications',
        'Architecture',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / Equivalent English Proof (if required)',
        'Statement of Purpose',
        'Passport-sized Photos',
        'Resume / CV',
      ],
      visaChecklist: [
        'University Acceptance Letter',
        'Proof of Tuition Fee Payment',
        'Proof of Financial Means (Bank Statement)',
        'Accommodation Proof in Cyprus',
        'Valid Travel Insurance',
        'Police Clearance Certificate',
        'Medical Certificate',
        'Visa Application Form (Completed)',
      ],
      faqs: [
        { question: 'Is IELTS mandatory for Cyprus student visa?', answer: 'Not always. Many universities in Cyprus offer conditional admission or accept alternative English proficiency proofs such as prior English-medium schooling.' },
        { question: 'Are Cyprus degrees recognized in Europe?', answer: 'Yes. Cyprus is an EU member state and its university degrees are recognized across the European Union and in many countries worldwide.' },
        { question: 'Is Cyprus safe for Nepali students?', answer: 'Cyprus is consistently ranked as one of the safest countries in Europe. It has a welcoming attitude toward international students and a large expat community.' },
        { question: 'Can I travel to Schengen countries from Cyprus?', answer: 'Cyprus is an EU member but not yet a full Schengen member. However, a Cyprus residence permit may ease travel to some EU destinations, and Schengen visa applications are more accessible from Cyprus.' },
      ],
    },
  },
  {
    id: 'fr',
    country: 'France',
    count: 9,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop',
    highlight: 'Hub of Art and Culture.',
    features: ['Low Tuition in Public Unis', 'Post-Study Work Visa', 'Schengen Visa Travel', 'Internship Opportunities', 'Housing Assistance (CAF)'],
    details: {
      overview: 'France is the fourth most popular destination for international students globally. Home to some of the world\'s oldest and most prestigious universities, France offers world-class education at remarkably low tuition costs in public institutions. With its rich culture, central Schengen location, and thriving job market, France is an excellent choice for ambitious students.',
      whyStudy: [
        'Very Low Tuition Fees at Public Universities (State-Subsidized)',
        'Post-Study Work Visa (APS – 1 to 2 Years)',
        'Access to Entire Schengen Zone for Travel',
        'Globally Ranked Grandes Écoles and Research Institutions',
        'CAF Housing Subsidy Available for International Students',
      ],
      intakes: ['September/October (Main Intake)', 'January/February (Some programs only)'],
      costs: {
        tuition: 'EUR 2,770 - 3,770/yr (Public); EUR 5,000 - 20,000/yr (Private/Grandes Écoles)',
        living: 'EUR 800 - 1,200 per month (Paris higher; other cities lower)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'French or English Proficiency Proof (Depending on program)',
        'Acceptance Letter via Campus France Nepal',
        'Statement of Purpose',
        'Proof of Financial Resources (EUR 615/month minimum)',
      ],
      workRights: 'International students can work up to 964 hours per year (approximately 20 hours per week) during studies. After graduation, the APS visa allows job searching and work experience.',
      popularCourses: [
        'Business & International Management',
        'Fashion Design & Luxury Brand Management',
        'Engineering & Technology',
        'Culinary Arts & Hospitality',
        'Political Science & International Relations',
        'Art, Architecture & Design',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'Language Proficiency Proof (French/English)',
        'Statement of Purpose',
        'Campus France Nepal Registration',
        'Letter of Recommendation',
        'Resume / CV',
      ],
      visaChecklist: [
        'Campus France Acceptance / Clearance',
        'University Admission Letter',
        'Proof of Financial Resources',
        'Accommodation Proof in France',
        'Travel Insurance (Schengen Standard)',
        'Police Clearance Certificate',
        'Passport-sized Photos',
        'Visa Application Fee Payment',
      ],
      faqs: [
        { question: 'Do I need to know French to study in France?', answer: 'Not necessarily. Many universities and Grandes Écoles offer programs fully taught in English, especially at the Master\'s level. However, learning French will greatly improve your social and professional experience.' },
        { question: 'What is Campus France?', answer: 'Campus France is the French government agency that manages international student applications. Nepali students must register and be interviewed through Campus France Nepal before applying for a student visa.' },
        { question: 'What is the APS visa?', answer: 'The APS (Autorisation Provisoire de Séjour) is a temporary stay permit granted to international graduates of French universities, allowing them to stay in France for up to 2 years to seek employment or start a business.' },
        { question: 'Is housing expensive in France?', answer: 'Paris is expensive, but other cities like Lyon, Toulouse, and Bordeaux are much more affordable. Additionally, the CAF (Caisse d\'Allocations Familiales) housing subsidy can significantly reduce monthly rent costs for eligible students.' },
      ],
    },
  },
  {
    id: 'ge',
    country: 'Georgia',
    count: 5,
    image: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?q=80&w=800&auto=format&fit=crop',
    highlight: 'Gateway to Europe.',
    features: ['No IELTS Required', 'Gap Accepted', 'Affordable Living Cost', 'Easy Admission Process', 'Schengen Transfer Options'],
    details: {
      overview: 'Georgia has rapidly emerged as a preferred destination for Nepali students seeking affordable, quality higher education in a European environment. With a straightforward visa process, no mandatory IELTS requirement for many programs, and a welcoming attitude toward international students, Georgia is an excellent stepping stone to a global career.',
      whyStudy: [
        'No IELTS Required for Most Programs',
        'Academic Gaps Accepted – Ideal for Gap Year Students',
        'Very Affordable Tuition and Living Costs',
        'English-Medium Medical and Business Programs',
        'Easy, Transparent Visa Process',
      ],
      intakes: ['September/October (Main Intake)', 'February (Spring Intake – Some Universities)'],
      costs: {
        tuition: 'USD 2,500 - 6,000 per year (Bachelor/Master)',
        living: 'USD 300 - 500 per month',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: Interview-based (IELTS not always mandatory)',
        'Acceptance Letter from a Georgian University',
        'Gap Year Explanation Letter (If applicable)',
        'Proof of Financial Means',
      ],
      workRights: 'International students in Georgia are generally permitted to work part-time, though regulations may vary. Students are advised to confirm work rights with their institution.',
      popularCourses: [
        'Medicine (MBBS) – Globally Recognized',
        'Business Administration',
        'Computer Science & IT',
        'Dentistry',
        'Pharmacy',
        'Tourism & Hospitality',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'English Interview Completion (University-specific)',
        'Gap Explanation Letter (If applicable)',
        'Statement of Purpose',
        'Passport-sized Photos',
      ],
      visaChecklist: [
        'University Admission Letter',
        'Proof of Financial Means',
        'Hotel/Accommodation Booking in Georgia',
        'Valid Travel Insurance',
        'Police Clearance Certificate',
        'Passport-sized Photos',
        'Visa Application Form',
        'Return Flight Ticket Proof',
      ],
      faqs: [
        { question: 'Is IELTS mandatory for Georgia?', answer: 'No. Most universities in Georgia do not require IELTS. Admission is often based on a short English interview conducted by the university online or in person.' },
        { question: 'Is a gap year a problem for Georgia admission?', answer: 'No. Georgia is one of the few destinations that readily accepts students with academic gaps. A brief explanation letter is usually sufficient.' },
        { question: 'Are Georgian medical degrees valid internationally?', answer: 'Yes. Medical degrees from recognized Georgian universities are listed in the WHO directory and are eligible for licensing exams in many countries including the USMLE, PLAB, and Nepal Medical Council.' },
        { question: 'How is the cost of living in Georgia?', answer: 'Georgia is one of the most affordable countries for international students. Monthly expenses including accommodation, food, and transport typically range between USD 300 to 500.' },
      ],
    },
  },
  {
    id: 'de',
    country: 'Germany',
    count: 15,
    image: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?q=80&w=800&auto=format&fit=crop',
    highlight: 'Innovation & Engineering hub.',
    features: ['Free/Low Tuition Fees', '18-mo Job Search Visa', 'Strong Economy', 'Schengen Visa Travel', 'Part-time Work Allowed'],
    details: {
      overview: 'Germany is Europe\'s largest economy and one of the most sought-after study destinations in the world. Famous for its engineering excellence, research output, and tuition-free education at public universities, Germany offers outstanding value and career prospects. The country actively welcomes skilled international graduates to contribute to its workforce.',
      whyStudy: [
        'No Tuition Fees at Most Public Universities',
        '18-Month Job Seeker Visa After Graduation',
        'Home to World-Renowned Research Institutions',
        'Strong Industry-University Partnerships',
        'Gateway to the Entire Schengen Zone',
      ],
      intakes: ['October (Winter Semester – Main Intake)', 'April (Summer Semester – Limited Programs)'],
      costs: {
        tuition: 'EUR 0 - 500/semester (Public); EUR 5,000 - 20,000/yr (Private)',
        living: 'EUR 850 - 1,200 per month (varies by city)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'German or English Proficiency Proof (B1/B2 German for German-taught; IELTS 6.0+ for English-taught)',
        'University Admission Letter (Zulassung)',
        'APS Certificate (Academic Evaluation for Nepali Students)',
        'Blocked Account (Sperrkonto) – EUR 11,208 per year',
      ],
      workRights: 'International students in Germany can work 120 full days or 240 half days per year. After graduation, the 18-month job seeker visa allows graduates to remain in Germany to find employment.',
      popularCourses: [
        'Mechanical & Automotive Engineering',
        'Computer Science & Informatics',
        'Electrical Engineering',
        'Business Administration & Economics',
        'Architecture & Urban Planning',
        'Natural Sciences & Research',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'APS Certificate (Mandatory for Nepali Students)',
        'Language Proficiency Certificate (German/English)',
        'Statement of Purpose (Motivationsschreiben)',
        'Letter of Recommendation',
        'Resume / CV (Europass Format Preferred)',
      ],
      visaChecklist: [
        'University Admission Letter',
        'Blocked Account (Sperrkonto) Proof – EUR 11,208',
        'APS Certificate',
        'Language Proficiency Proof',
        'Health Insurance Certificate',
        'Biometric Passport Photos',
        'Police Clearance Certificate',
        'Visa Application Form (Completed)',
      ],
      faqs: [
        { question: 'What is an APS Certificate?', answer: 'The APS (Akademische Prüfstelle) Certificate is a mandatory academic verification document for Nepali students applying to German universities. It requires submitting original certificates and attending an interview at the APS office in Kathmandu.' },
        { question: 'What is a Blocked Account (Sperrkonto)?', answer: 'A Sperrkonto is a German blocked bank account where you must deposit EUR 11,208 before applying for your visa. This proves you can cover your living expenses. You can withdraw a fixed amount each month after arrival.' },
        { question: 'Do I need to learn German?', answer: 'It depends on your program. Many Master\'s programs are available in English. However, learning German (at least B1 level) is highly recommended for daily life and employment prospects.' },
        { question: 'Can I stay in Germany after graduation?', answer: 'Yes. Germany offers an 18-month Job Seeker Visa after graduation, which allows you to look for work related to your field of study. If you find a job, you can then apply for a work permit and eventually PR.' },
      ],
    },
  },
  {
    id: 'ie',
    country: 'Ireland',
    count: 7,
    image: 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?q=80&w=800&auto=format&fit=crop',
    highlight: 'Silicon Valley of Europe.',
    features: ['2-Year Stay Back', 'English Speaking Country', 'Tech Hub Careers', 'High Quality Education', 'Part-time Work Rights'],
    details: {
      overview: 'Ireland is a thriving hub for technology, pharmaceuticals, and finance, home to the European headquarters of Google, Facebook, Apple, and many more global giants. As an English-speaking EU country with a 2-year graduate stay-back option, Ireland offers exceptional career opportunities for international students after graduation.',
      whyStudy: [
        '2-Year Graduate Stay Permission (Third Level Graduate Scheme)',
        'English-Speaking EU Country',
        'European Headquarters of Major Tech Companies',
        'High-Quality, Internationally Recognized Degrees',
        'Vibrant, Student-Friendly Culture',
      ],
      intakes: ['September (Main Intake)', 'January/February (Some Programs)'],
      costs: {
        tuition: 'EUR 9,000 - 25,000 per year (Bachelor/Master)',
        living: 'EUR 1,000 - 1,500 per month (Dublin higher)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.0+) or equivalent',
        'University Acceptance Letter',
        'Statement of Purpose',
        'Proof of Financial Means (EUR 7,000 minimum)',
      ],
      workRights: 'International students can work up to 20 hours per week during academic term and 40 hours per week during holidays. The 2-year Third Level Graduate Scheme allows full-time work post-graduation.',
      popularCourses: [
        'Computer Science & Data Analytics',
        'Business & Finance',
        'Pharmaceutical Science',
        'Engineering',
        'Nursing & Healthcare',
        'Marketing & Digital Media',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / English Proficiency Score',
        'Statement of Purpose',
        'Letter of Recommendation (Min 2)',
        'Resume / CV',
      ],
      visaChecklist: [
        'University Acceptance Letter',
        'Proof of Tuition Fee Payment (Full or Partial)',
        'Bank Statement (Showing Sufficient Funds)',
        'Medical Insurance (VHI or equivalent)',
        'Police Clearance Certificate',
        'Passport-sized Photos',
        'Completed Visa Application (AVATS)',
        'Return Flight Ticket (Optional but recommended)',
      ],
      faqs: [
        { question: 'What is the Third Level Graduate Scheme in Ireland?', answer: 'It is a stay-back permission that allows non-EEA graduates of Irish institutions to remain in Ireland for 2 years to seek graduate-level employment. This applies to degree and higher qualifications.' },
        { question: 'Is Ireland expensive for students?', answer: 'Dublin is relatively expensive compared to other Irish cities. However, cities like Cork, Galway, and Limerick offer much more affordable living options with excellent universities.' },
        { question: 'Can I bring my family to Ireland on a student visa?', answer: 'Dependent visas for family members are not automatically granted with an Irish student visa. However, spouses may apply separately for a join family permission in some cases.' },
        { question: 'Does Ireland have PR pathways for graduates?', answer: 'While there is no direct PR pathway specifically for graduates, working in Ireland on the graduate scheme and then obtaining a work permit can eventually lead to long-term residency and citizenship through the naturalization process.' },
      ],
    },
  },
  {
    id: 'jp',
    country: 'Japan',
    count: 13,
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=800&auto=format&fit=crop',
    highlight: 'Technology meets Tradition.',
    features: ['High Visa Success Rate', 'Part-time Work Allowed', 'Career Opportunities', 'Safe Environment', 'Scholarships Available'],
    details: {
      overview: 'Japan is one of the most technologically advanced and culturally rich countries in the world. For Nepali students, Japan offers high visa success rates, a safe and disciplined environment, and strong employment opportunities especially in IT, manufacturing, and services. Japanese language skills open up an even wider range of career paths.',
      whyStudy: [
        'High Visa Approval Rate for Nepali Students',
        'Part-time Work Allowed (28 hrs/week)',
        'Safe, Disciplined, and Well-Organized Society',
        'MEXT and University Scholarships Available',
        'Strong Job Market in Technology and Manufacturing',
      ],
      intakes: ['April (Main Intake – Japanese Academic Year)', 'October (Secondary Intake)'],
      costs: {
        tuition: 'JPY 500,000 - 1,500,000 per year (Language School/University)',
        living: 'JPY 80,000 - 130,000 per month',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'Japanese Language Proficiency: NAT-TEST N5 minimum (for language school)',
        'Certificate of Eligibility (COE) from Japanese Immigration',
        'Proof of Financial Sponsorship',
        'Academic Certificates Translated to Japanese',
      ],
      workRights: 'International students in Japan can work up to 28 hours per week during academic sessions and full-time during official school holidays, with a valid work permission stamp on their residence card.',
      popularCourses: [
        'Japanese Language Studies',
        'Information Technology & Computer Science',
        'Business & Commerce',
        'Engineering & Robotics',
        'Culinary Arts',
        'Design & Animation',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates (Translated)',
        'NAT-TEST or JLPT Score (N5 minimum)',
        'Bank Certificate / Sponsor Financial Proof',
        'Certificate of Enrollment (Previous School)',
        'Passport-sized Photos',
        'Resume / CV',
      ],
      visaChecklist: [
        'Certificate of Eligibility (COE) – issued by Japanese school',
        'Passport (Valid 6+ months)',
        'Visa Application Form (Downloaded from Embassy)',
        'Photo (4cm x 3cm, white background)',
        'Sponsor\'s Financial Documents (Bank Balance, Income Proof)',
        'Sponsor\'s Relationship Certificate',
        'Police Clearance Certificate',
        'Return Envelope (for passport return by post)',
      ],
      faqs: [
        { question: 'What is a Certificate of Eligibility (COE) for Japan?', answer: 'The COE is the most critical document in the Japan student visa process. It is issued by the Japanese Regional Immigration Bureau after the school applies on your behalf. Without a COE, you cannot apply for a visa at the Japanese Embassy.' },
        { question: 'Do I need to know Japanese to study in Japan?', answer: 'For Japanese language schools, basic Japanese (NAT N5 level) is typically required. For universities with English-medium programs, Japanese is not mandatory, but it is highly beneficial for daily life and employment.' },
        { question: 'What are part-time work options in Japan?', answer: 'Students commonly work in convenience stores (konbini), restaurants, factories, or delivery services. Many students earn JPY 1,000 - 1,500 per hour.' },
        { question: 'Are there scholarships available in Japan?', answer: 'Yes. The Japanese Government (MEXT) scholarship is highly prestigious. Many private universities also offer internal scholarships. Additional support is available through JASSO (Japan Student Services Organization).' },
      ],
    },
  },
  {
    id: 'mt',
    country: 'Malta',
    count: 5,
    image: 'https://images.unsplash.com/photo-1597500330999-7227d6200236?q=80&w=800&auto=format&fit=crop',
    highlight: 'English speaking Mediterranean gem.',
    features: ['Schengen Member State', 'Low Tuition Fees', 'English Speaking', 'Work Permit Possibilities', 'Simple Visa Process'],
    details: {
      overview: 'Malta is a small but strategically located island nation in the Mediterranean Sea and a full EU and Schengen member state. As an English-speaking country with affordable tuition fees and a simple student visa process, Malta is gaining popularity among Nepali students seeking a European education without the high costs of Western Europe.',
      whyStudy: [
        'Full EU and Schengen Member – Travel Across Europe',
        'English as an Official Language',
        'Affordable Tuition Compared to Most of Europe',
        'Simple and Transparent Student Visa Process',
        'High Safety and Quality of Life',
      ],
      intakes: ['July (Main Intake)', 'September (Secondary Intake)'],
      costs: {
        tuition: 'EUR 5,500 - 12,000 per year (Bachelor/Master)',
        living: 'EUR 700 - 1,000 per month',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (5.5+) or equivalent',
        'University Acceptance Letter',
        'Proof of Financial Means',
        'Accommodation Proof in Malta',
      ],
      workRights: 'International students from non-EU countries may apply for a part-time work permit after enrollment. Work is typically allowed up to 20 hours per week during studies.',
      popularCourses: [
        'Business & Management',
        'Information Technology',
        'Hospitality & Tourism Management',
        'English Language Programs',
        'Arts & Design',
        'Healthcare',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / English Proficiency Score',
        'Statement of Purpose',
        'Resume / CV',
        'Passport-sized Photos',
      ],
      visaChecklist: [
        'University Acceptance Letter',
        'Proof of Tuition Fee Payment',
        'Bank Statement (Financial Proof)',
        'Accommodation Letter in Malta',
        'Travel Insurance (Schengen Standard)',
        'Police Clearance Certificate',
        'Completed Visa Application Form',
        'Passport-sized Photos',
      ],
      faqs: [
        { question: 'Is Malta part of the Schengen Area?', answer: 'Yes. Malta is a full Schengen member, which means a Maltese student residence permit allows easier travel to other Schengen countries.' },
        { question: 'Is English widely spoken in Malta?', answer: 'Yes. Maltese and English are both official languages. All university programs and daily life interactions are widely conducted in English.' },
        { question: 'Is it easy to get a student visa for Malta?', answer: 'Yes, Malta has one of the more straightforward student visa processes in Europe. With a proper admission letter and financial proof, the process is relatively fast.' },
        { question: 'Can I work in Malta as a student?', answer: 'Non-EU students need a separate work permit to work in Malta. This can be applied for after enrollment and is generally approved for up to 20 hours per week.' },
      ],
    },
  },
  {
    id: 'nl',
    country: 'Netherlands',
    count: 8,
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?q=80&w=800&auto=format&fit=crop',
    highlight: 'Creative & International.',
    features: ['Orientation Year Visa', 'English Taught Programs', 'Central European Location', 'Innovative Teaching', 'High English Proficiency'],
    details: {
      overview: 'The Netherlands is one of the most internationally oriented countries in Europe, home to a highly educated and English-proficient population. Dutch universities are globally recognized for innovative, problem-based learning methods. With a central location in Europe and strong ties to global industries, the Netherlands is an excellent choice for internationally minded students.',
      whyStudy: [
        'One of the Highest Numbers of English-Taught Programs in Non-English Speaking Europe',
        'Orientation Year Visa (Zoekjaar) After Graduation',
        'Innovative Problem-Based Learning Approach',
        'Central Location – Easy Travel Across Europe',
        'High Quality of Life and Student Support',
      ],
      intakes: ['September (Main Intake)', 'February (Some Programs)'],
      costs: {
        tuition: 'EUR 8,000 - 20,000 per year (Non-EU Students)',
        living: 'EUR 900 - 1,300 per month',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.0+) or equivalent',
        'University Acceptance Letter',
        'Statement of Purpose / Motivation Letter',
        'Proof of Financial Means (EUR 11,000 minimum)',
      ],
      workRights: 'International students can work up to 16 hours per week during studies. Full-time work is permitted during June, July, and August. The Orientation Year Visa allows 12 months of job searching post-graduation.',
      popularCourses: [
        'Business, Economics & Finance',
        'Computer Science & Artificial Intelligence',
        'International Law',
        'Creative Arts & Design',
        'Engineering & Water Management',
        'Agriculture & Life Sciences (Wageningen University)',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / English Proficiency Score',
        'Motivation Letter',
        'Letter of Recommendation',
        'Portfolio (For Arts/Design programs)',
        'Resume / CV',
      ],
      visaChecklist: [
        'University Acceptance / MVV Sponsorship Letter',
        'Proof of Financial Means (EUR 11,000+)',
        'Health Insurance (Dutch Standard)',
        'Biometric Passport Photos',
        'Police Clearance Certificate',
        'Completed Visa/MVV Application',
        'Tuition Fee Payment Proof',
      ],
      faqs: [
        { question: 'What is the Orientation Year Visa (Zoekjaar)?', answer: 'The Zoekjaar is a one-year residence permit allowing graduates from Dutch universities to stay in the Netherlands and search for work. If you find a job matching your degree level, you can apply for a work permit.' },
        { question: 'How many English-taught programs are available in the Netherlands?', answer: 'The Netherlands has over 2,000 English-taught programs, making it one of the leading non-English-speaking countries for international students who want to study in English.' },
        { question: 'Is the cost of living high in the Netherlands?', answer: 'It is moderate compared to the UK but higher than Eastern Europe. Amsterdam is the most expensive city. Smaller cities like Groningen, Eindhoven, and Tilburg offer more affordable living.' },
        { question: 'What is a MVV visa for the Netherlands?', answer: 'A MVV (Machtiging tot Voorlopig Verblijf) is a provisional residence permit / entry visa required by non-EU students before traveling to the Netherlands for studies. Your university will sponsor your application through IND (Dutch Immigration).' },
      ],
    },
  },
  {
    id: 'nz',
    country: 'New Zealand',
    count: 6,
    image: 'https://images.unsplash.com/photo-1469521669194-babb45599def?q=80&w=800&auto=format&fit=crop',
    highlight: 'Adventure and Education.',
    features: ['Post-Study Work Rights', 'High Quality of Life', 'Safe & Peaceful', 'Research Opportunities', 'Spouse Visa Options'],
    details: {
      overview: 'New Zealand is a safe, clean, and breathtakingly beautiful country that offers an outstanding quality of life alongside a world-class education system. Ranked highly for research and innovation, New Zealand universities are globally respected, and the country offers generous post-study work rights that make it attractive for career-focused students.',
      whyStudy: [
        'Post-Study Open Work Visa (Up to 3 Years)',
        'Extremely Safe and Peaceful Environment',
        'High-Quality Research Programs',
        'Spouse Eligible for Open Work Permit',
        'Stunning Natural Environment and High Lifestyle Quality',
      ],
      intakes: ['February (Main Intake)', 'July (Mid-Year Intake)'],
      costs: {
        tuition: 'NZD 22,000 - 35,000 per year (Bachelor/Master)',
        living: 'NZD 15,000 - 20,000 per year',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.0+) or PTE (50+)',
        'University Acceptance Letter',
        'Statement of Purpose',
        'Proof of Financial Funds',
      ],
      workRights: 'International students can work up to 20 hours per week during academic terms and full-time during scheduled breaks. After graduation, an open work visa allows work anywhere in New Zealand for up to 3 years.',
      popularCourses: [
        'Agriculture & Environmental Science',
        'Information Technology',
        'Business & Management',
        'Engineering',
        'Film & Creative Arts',
        'Nursing & Healthcare',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / PTE Score Report',
        'Statement of Purpose',
        'Letter of Recommendation',
        'Resume / CV',
        'Work Experience Letter (If applicable)',
      ],
      visaChecklist: [
        'Offer of Place (Acceptance Letter from University)',
        'Proof of Financial Funds',
        'Valid Passport',
        'Medical and Chest X-Ray (If required)',
        'Police Clearance Certificate',
        'Passport-sized Photos',
        'Visa Application Fee Payment',
        'Health Insurance Evidence',
      ],
      faqs: [
        { question: 'How long is the post-study work visa in New Zealand?', answer: 'Graduates from New Zealand universities can apply for a Post-Study Open Work Visa, which allows them to work for any employer in any location in New Zealand for up to 3 years depending on their qualification level.' },
        { question: 'Can my spouse work in New Zealand on my student visa?', answer: 'Yes. Spouses and de-facto partners of eligible international students can apply for an open work visa, allowing them to work for any employer in New Zealand.' },
        { question: 'Is New Zealand safe for international students?', answer: 'Yes. New Zealand consistently ranks as one of the safest countries in the world. It has very low crime rates and a culturally inclusive society that is welcoming to international students.' },
        { question: 'What English score do I need?', answer: 'Most universities require an IELTS overall band of 6.0 with no band less than 5.5, or PTE 50. Some programs such as nursing or medicine may require higher scores.' },
      ],
    },
  },
  {
    id: 'kr',
    country: 'South Korea',
    count: 11,
    image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=800&auto=format&fit=crop',
    highlight: 'Leading in Technology.',
    features: ['High-Tech Industry Jobs', 'Generous Scholarships', 'Affordable Tuition', 'Cultural Experience', 'Part-time Work Rights'],
    details: {
      overview: 'South Korea has emerged as a global leader in technology, electronics, and pop culture. For Nepali students, Korea offers an exciting blend of affordable education, generous government scholarships, and strong employment opportunities in tech and manufacturing. BrightPath Nepal has been placing students in Korea since its founding year.',
      whyStudy: [
        'GKS (Global Korea Scholarship) – Fully Funded Government Scholarship',
        'Affordable Tuition and Living Costs',
        'Strong IT, Electronics, and Manufacturing Industry',
        'Korean Language Skills Highly Valued for Employment',
        'Vibrant K-Culture and Exciting Campus Life',
      ],
      intakes: ['March (Spring – Main Intake)', 'September (Fall Intake)'],
      costs: {
        tuition: 'KRW 3,000,000 - 8,000,000 per semester (Bachelor/Master)',
        living: 'KRW 500,000 - 900,000 per month',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'Korean Language Proficiency: TOPIK Level 2-3 (for Korean-taught programs)',
        'English Proficiency: IELTS (5.5+) for English-taught programs',
        'University Acceptance Letter',
        'Proof of Financial Sponsorship',
      ],
      workRights: 'International students in South Korea can work up to 20 hours per week during the academic semester. During vacation periods, there is no restriction on working hours.',
      popularCourses: [
        'Korean Language Studies',
        'Computer Science & Software Engineering',
        'Business & International Trade',
        'Electronics & Semiconductor Engineering',
        'Design & K-Content (Media, Animation)',
        'Biomedical & Health Sciences',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'TOPIK Score (If applicable)',
        'IELTS / English Proficiency Score (For English programs)',
        'Statement of Purpose',
        'Letter of Recommendation',
        'Resume / CV',
        'Bank Certificate / Sponsor Financial Proof',
      ],
      visaChecklist: [
        'University Admission Letter',
        'Certificate of Admission (Standard Form D)',
        'Financial Proof (Bank Balance / Sponsor)',
        'Sponsor Relationship Documents',
        'Police Clearance Certificate',
        'Passport-sized Photos',
        'Visa Application Form (D-2 or D-4)',
        'Academic Documents (Notarized)',
      ],
      faqs: [
        { question: 'What is the GKS Scholarship?', answer: 'The Global Korea Scholarship (GKS) is a fully-funded South Korean government scholarship for international students. It covers tuition, living expenses, round-trip airfare, and a settlement allowance. It is highly competitive but well worth applying for.' },
        { question: 'Do I need to learn Korean before going to South Korea?', answer: 'It is highly recommended. For Korean-taught university programs, TOPIK Level 3 or above is typically required. Language schools (D-4 visa) allow you to go to Korea first and learn Korean before entering a degree program.' },
        { question: 'What is the D-2 vs D-4 visa for Korea?', answer: 'D-4 is a General Training Visa for students attending language institutes. D-2 is the Student Visa for students enrolled in degree programs at Korean universities. Most Nepali students begin on a D-4 visa and then transfer to D-2.' },
        { question: 'Are Korean degrees internationally recognized?', answer: 'Yes. Korean universities like Seoul National University, KAIST, POSTECH, and Yonsei are globally ranked and their degrees are recognized internationally, especially in Asia, the Middle East, and in STEM fields.' },
      ],
    },
  },
  {
    id: 'ae',
    country: 'UAE',
    count: 10,
    image: 'https://images.unsplash.com/photo-1546412414-e1885259563a?q=80&w=800&auto=format&fit=crop',
    highlight: 'Global Business Hub.',
    features: ['No Bank Balance Req', 'Easy Visa Process', 'Tax-Free Income Jobs', 'International Campuses', 'Safe & Modern City'],
    details: {
      overview: 'The United Arab Emirates has become a global hub for education, business, and innovation. Home to international branch campuses of top global universities, a tax-free economy, and a cosmopolitan lifestyle, the UAE is an increasingly attractive destination for Nepali students seeking a world-class education in the heart of the Middle East.',
      whyStudy: [
        'International Branch Campuses of Top Global Universities',
        'Tax-Free Income – Strong Financial Prospects After Graduation',
        'No Minimum Bank Balance for Admission (Unlike Many Countries)',
        'Simple and Fast Visa Process',
        'Safe, Modern, and Cosmopolitan Environment',
      ],
      intakes: ['September (Main Intake)', 'January/February (Secondary Intake)'],
      costs: {
        tuition: 'AED 40,000 - 90,000 per year (Bachelor/Master)',
        living: 'AED 3,000 - 5,000 per month (Dubai/Abu Dhabi)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (5.5 - 6.0+) depending on university',
        'University Acceptance Letter',
        'UAE Entry Visa (Sponsored by University)',
        'Emirates ID Application Upon Arrival',
      ],
      workRights: 'International students in the UAE may work part-time with a No Objection Certificate (NOC) from their university. Many students also find internship placements through their institutions.',
      popularCourses: [
        'Business Administration & International Management',
        'Engineering (Civil, Electrical, Mechanical)',
        'Media & Mass Communication',
        'Computer Science & Cybersecurity',
        'Architecture & Interior Design',
        'Finance & Accounting',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / English Proficiency Score',
        'Statement of Purpose',
        'Passport-sized Photos',
        'Resume / CV',
      ],
      visaChecklist: [
        'University Acceptance Letter',
        'University-sponsored Visa Application',
        'Passport (Valid 6+ months)',
        'Passport-sized Photos',
        'Medical Fitness Certificate',
        'Emirates ID Application (On Arrival)',
        'Health Insurance (University/Personal)',
        'Visa Application Fee Payment',
      ],
      faqs: [
        { question: 'Do I need a high bank balance for a UAE student visa?', answer: 'No. Unlike countries like Australia or the UK, the UAE student visa process is primarily sponsored by the university, so students do not typically need to show a large personal bank balance as part of the application.' },
        { question: 'Are there world-ranked universities in the UAE?', answer: 'Yes. The UAE is home to international branch campuses of universities such as NYU Abu Dhabi, Sorbonne Abu Dhabi, Heriot-Watt Dubai, and the University of Birmingham Dubai, among many others.' },
        { question: 'Is it easy to get part-time work in the UAE as a student?', answer: 'Part-time work requires a No Objection Certificate (NOC) from your university and a temporary work permit. In practice, many students work informally or through university-arranged internships.' },
        { question: 'Is the UAE safe for Nepali students?', answer: 'Yes. The UAE is one of the safest countries in the world with very low crime rates. There is also a large and well-established Nepali community in the UAE, making the transition much easier.' },
      ],
    },
  },
  {
    id: 'uk',
    country: 'United Kingdom',
    count: 15,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop',
    highlight: 'Academic Excellence.',
    features: ['Graduate Route (2 yrs)', 'Short Masters (1 yr)', 'World Renowned Unis', 'No IELTS Options', 'Spouse Visa Allowed'],
    details: {
      overview: 'The United Kingdom is home to some of the world\'s most prestigious universities, including Oxford, Cambridge, Imperial College, and UCL. With a 2-year Graduate Route visa, 1-year master\'s programs, and spouse visa options, the UK continues to be one of the top choices for Nepali students seeking academic excellence and global recognition.',
      whyStudy: [
        '2-Year Graduate Route Visa After Graduation',
        'Shorter Programs – 3-Year Bachelor\'s, 1-Year Master\'s',
        'Home to Oxford, Cambridge, and 4 other Top-10 Global Universities',
        'Spouse Eligible for Dependent Visa (for Postgraduate Students)',
        'NHS Health Coverage via IHS',
      ],
      intakes: ['September/October (Main Intake)', 'January (Secondary Intake – Selected Programs)'],
      costs: {
        tuition: 'GBP 10,000 - 30,000 per year (Bachelor/Master)',
        living: 'GBP 1,000 - 1,500 per month (London higher)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.0 - 6.5+) or Pearson/SELT',
        'CAS (Confirmation of Acceptance for Studies) from University',
        'Proof of Financial Funds (GBP 1,334/month for up to 9 months)',
        'IHS (Immigration Health Surcharge) Payment',
      ],
      workRights: 'International students can work up to 20 hours per week during term time and full-time during official vacations. The Graduate Route visa allows 2 years of unrestricted work in the UK after graduation.',
      popularCourses: [
        'Law & International Law',
        'Business & Finance (CFA, ACCA Pathways)',
        'Computer Science & Artificial Intelligence',
        'Medicine & Biomedical Sciences',
        'Architecture',
        'Social Sciences & Political Science',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'IELTS / UKVI / Pearson Score Report',
        'Statement of Purpose',
        'Letter of Recommendation (Min 2)',
        'Resume / CV',
        'Work Experience Letter (If applicable)',
      ],
      visaChecklist: [
        'CAS (Confirmation of Acceptance for Studies)',
        'Financial Evidence (Bank Statement)',
        'IHS (Immigration Health Surcharge) Payment Receipt',
        'ATAS Certificate (For certain science/tech subjects)',
        'Tuberculosis (TB) Test Result',
        'Passport-sized Photos',
        'Police Clearance Certificate',
        'Visa Application Fee Payment',
      ],
      faqs: [
        { question: 'What is the Graduate Route in the UK?', answer: 'The Graduate Route is a 2-year unsponsored post-study visa (3 years for PhD graduates) that allows international graduates to live and work in the UK without needing a job offer. It came into effect in July 2021.' },
        { question: 'Can my spouse come to the UK with me?', answer: 'Yes, for postgraduate students (Master\'s and above). Spouses and children can apply as dependants on your UK student visa. Dependant spouses are also permitted to work full-time in the UK.' },
        { question: 'What is IHS?', answer: 'The Immigration Health Surcharge (IHS) is a mandatory fee paid upfront by international students to access the UK National Health Service (NHS) during their stay. As of 2024, this is GBP 776 per year.' },
        { question: 'Is IELTS mandatory for a UK student visa?', answer: 'Not always. Some universities accept Pearson PTE Academic (UKVI), Trinity College London SELT tests, or even internal English assessments. Some universities accept online IELTS. Always check the UKVI-approved test list.' },
      ],
    },
  },
  {
    id: 'us',
    country: 'USA',
    count: 14,
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=800&auto=format&fit=crop',
    highlight: 'Land of Opportunity.',
    features: ['OPT/CPT Work Rights', 'STEM OPT Extension', 'Huge Scholarship Funds', 'Flexible Curriculum', 'Global Career Recognition'],
    details: {
      overview: 'The United States hosts the largest number of international students in the world and is home to the most globally prestigious universities. With a flexible credit-based education system, massive scholarship funds, and an Optional Practical Training (OPT) program that can extend to 3 years for STEM graduates, the USA remains the ultimate destination for ambitious students.',
      whyStudy: [
        'Home to the World\'s Top Ranked Universities (MIT, Harvard, Stanford)',
        'OPT Work Authorization for 1 Year (3 Years for STEM Programs)',
        'Massive Financial Aid and Scholarship Opportunities',
        'Flexible Curriculum – Change Majors and Explore Subjects',
        'Globally Recognized and Respected Degrees',
      ],
      intakes: ['August/September (Fall – Major Intake)', 'January (Spring – Secondary Intake)'],
      costs: {
        tuition: 'USD 15,000 - 55,000 per year (Bachelor/Master)',
        living: 'USD 10,000 - 20,000 per year (varies by state)',
      },
      requirements: [
        'Valid Passport and Academic Documents',
        'English Proficiency: IELTS (6.5+), TOEFL (80+), or Duolingo (105+)',
        'SAT/ACT (for Undergraduate at selective schools)',
        'GRE/GMAT (for select Graduate programs)',
        'F-1 Visa with I-20 from SEVP-approved institution',
        'Proof of Financial Support',
      ],
      workRights: 'F-1 students can work on-campus up to 20 hours per week. OPT allows 12 months of off-campus work after graduation. STEM graduates are eligible for a 24-month OPT extension, for a total of 36 months.',
      popularCourses: [
        'Computer Science & Artificial Intelligence',
        'Business Administration & MBA',
        'Engineering (Software, Electrical, Biomedical)',
        'Data Science & Analytics',
        'Medicine & Pre-Med Sciences',
        'Law (LLM for International Students)',
      ],
      admissionChecklist: [
        'Passport (Scanned Copy)',
        'Academic Transcripts & Certificates',
        'TOEFL / IELTS / Duolingo Score Report',
        'SAT / ACT / GRE / GMAT Score (If required)',
        'Statement of Purpose',
        'Letter of Recommendation (Min 2-3)',
        'Resume / CV',
        'Financial Affidavit of Support',
      ],
      visaChecklist: [
        'I-20 Form (from SEVP-Approved School)',
        'DS-160 Visa Application (Completed Online)',
        'SEVIS Fee Payment Receipt (I-901)',
        'Financial Proof (Sponsor Bank Statement)',
        'Visa Interview Appointment Confirmation',
        'Passport-sized Photos (US Specification)',
        'Academic Documents',
        'Visa Application Fee (MRV Fee) Payment',
      ],
      faqs: [
        { question: 'What is OPT and STEM OPT?', answer: 'Optional Practical Training (OPT) allows F-1 students to work in the USA for 12 months in a field related to their degree after graduation. STEM OPT is a 24-month extension available to graduates of STEM-designated programs, totaling 36 months of work authorization.' },
        { question: 'What is a SEVIS fee and I-20?', answer: 'The I-20 is a certificate of eligibility for F-1 status issued by your US school. The SEVIS (Student Exchange Visitor Information System) fee of USD 350 must be paid before your visa interview.' },
        { question: 'Is financial aid available for international students in the US?', answer: 'Yes, though it varies greatly by institution. Some universities like MIT, Harvard, and Yale are need-blind for international students and offer substantial financial aid. Merit-based scholarships are available at hundreds of universities.' },
        { question: 'Is a US student visa interview mandatory?', answer: 'Yes. All F-1 visa applicants (with very few exceptions) must attend an in-person interview at the US Embassy. The interview is typically short but requires confident, clear answers about your study plans and ties to Nepal.' },
      ],
    },
  },
];

export const LANGUAGES: LanguageClass[] = [
  { name: 'IELTS', icon: 'globe' },
  { name: 'PTE', icon: 'monitor' },
  { name: 'Duolingo', icon: 'feather' },
  { name: 'Korean', icon: 'book' },
  { name: 'Japanese', icon: 'sun' },
  { name: 'German', icon: 'map' },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sushant Sharma',
    role: 'University of Tokyo',
    content: '"BrightPath guided me through every step of my Japan student visa. The language classes were top-notch!"',
    avatar: 'https://picsum.photos/100/100?random=1',
  },
  {
    id: '2',
    name: 'Anjali Shrestha',
    role: 'Sydney University',
    content: '"I was confused about documentation, but they made it so simple. Got my visa in 2 weeks."',
    avatar: 'https://picsum.photos/100/100?random=2',
  },
  {
    id: '3',
    name: 'Rohan Maharjan',
    role: 'Seoul National Univ.',
    content: "\"The team is very professional and friendly. They helped me get a scholarship I didn't even know existed.\"",
    avatar: 'https://picsum.photos/100/100?random=3',
  },
];

export const MILESTONES: Milestone[] = [
  { year: '2019', title: 'Establishment', desc: 'Founded with a mission to guide students. Started South Korea program.' },
  { year: '2020', title: 'Pandemic Resilience', desc: 'Adapted to digital counseling during COVID-19, supporting students remotely.' },
  { year: '2022', title: 'Recovery & Growth', desc: 'Operations returned to full scale. Record number of visas approved.' },
  { year: '2023', title: 'New Horizons', desc: 'Expanded to UAE and Europe. Partnered with 50+ new universities.' },
  { year: '2025', title: 'Expansion', desc: 'New corporate office launched. Integrated advanced language labs.' },
];

const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Top 5 Reasons to Study in Australia',
    excerpt: 'Discover why Australia remains a top destination for international students with its world-class education system and vibrant lifestyle.',
    content: `Australia has consistently ranked as one of the top destinations for international students worldwide. But what exactly makes it so special?\n\n1. World-Class Education System: Home to many universities featured in the global top 100, Australian institutions offer rigorous academic standards and cutting-edge research opportunities.\n\n2. Diversity and Inclusion: Australia is a melting pot of cultures, making it incredibly welcoming for students from Nepal and beyond.\n\n3. Post-Study Work Opportunities: The Australian government offers attractive stay-back options for graduates, allowing them to gain valuable international work experience.\n\n4. High Quality of Life: From the pristine beaches of Sydney to the cultural hub of Melbourne, students enjoy a lifestyle that is both safe and exciting.\n\n5. Specialized Courses: Whether you are interested in Marine Biology, Engineering, or Hospitality, Australian universities offer specialized programs tailored to market demands.\n\nBrightPath Nepal provides end-to-end guidance for students aiming for Australia. Visit our main office for a free profile assessment.`,
    date: 'Oct 24, 2024',
    author: 'Sita Lamsal',
    category: 'Study Abroad',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=800&auto=format&fit=crop',
    slug: 'top-5-reasons-australia',
  },
  {
    id: '2',
    title: 'How to Secure a Full Scholarship in USA',
    excerpt: 'A comprehensive guide on applying for fully funded scholarships in US universities, including tips on SOPs and essays.',
    content: `Securing a full scholarship in the USA is a dream for many Nepali students. While competitive, it is entirely possible with the right strategy.\n\nStep 1: Start Early. Scholarship deadlines often fall much earlier than admission deadlines. Aim to start your search at least 12-18 months before you plan to enroll.\n\nStep 2: Focus on Academic Excellence. Most full scholarships are merit-based. High GPA and standardized test scores (SAT/ACT/GRE) are crucial.\n\nStep 3: Master the Personal Statement. Your SOP should tell a unique story that highlights your leadership potential and resilience.\n\nStep 4: Research Financial Aid. Many top-tier US colleges are 'need-blind' for international students, meaning they will provide full funding if you are accepted.\n\nStep 5: External Scholarships. Don't just look at university funding. Research Fulbright, Hubert Humphrey, and other international scholarship programs.\n\nAt BrightPath, we specialize in scholarship documentation. Our experts have helped hundreds of students secure significant financial aid in the US.`,
    date: 'Nov 12, 2024',
    author: 'Admin',
    category: 'Scholarships',
    image: 'https://images.unsplash.com/photo-1525921429624-479b6a26d84d?q=80&w=800&auto=format&fit=crop',
    slug: 'scholarship-guide-usa',
  },
  {
    id: '3',
    title: 'Understanding the Japan Student Visa Process',
    excerpt: 'Navigate the complexities of the Japanese student visa application. Learn about COE, documentation, and interview prep.',
    content: `Japan offers a unique blend of high-tech innovation and traditional culture. For Nepali students, it is an increasingly popular destination due to high visa success rates.\n\nThe process begins with the COE (Certificate of Eligibility). This is the most critical document, issued by the Japanese Immigration Bureau.\n\nTo obtain a COE, you must first apply to a Japanese language school or university. They will submit your documents to immigration on your behalf. Required documents typically include academic certificates, birth certificates, and solid financial proof of sponsorship.\n\nOnce the COE is granted, you can apply for the student visa at the Japanese Embassy in Kathmandu. Preparation is key—you should have basic Japanese language skills (NAT/JLPT N5 level) to ensure success.\n\nBrightPath Nepal offers intensive Japanese language classes and expert visa guidance for Japan. Join our next batch today.`,
    date: 'Dec 05, 2024',
    author: 'Admin',
    category: 'Visa Guide',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    slug: 'japan-visa-process',
  },
  {
    id: '4',
    title: 'IELTS vs PTE: Which test is right for you?',
    excerpt: 'Comparing the two most popular English proficiency tests to help you decide which one matches your skills better.',
    content: 'Choosing between IELTS and PTE can be tricky. IELTS is more traditional while PTE is computer-based...',
    date: 'Jan 10, 2025',
    author: 'BrightPath Expert',
    category: 'Test Prep',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=800&auto=format&fit=crop',
    slug: 'ielts-vs-pte',
  },
  {
    id: '5',
    title: 'The Rise of European Higher Education',
    excerpt: 'Why more students are choosing countries like Germany and France for their degrees in 2025.',
    content: 'Europe is becoming the new hub for international students due to low tuition and high lifestyle quality...',
    date: 'Feb 15, 2025',
    author: 'Admissions Team',
    category: 'Study Abroad',
    image: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?q=80&w=800&auto=format&fit=crop',
    slug: 'study-in-europe',
  },
  {
    id: '6',
    title: 'Post-Study Work Rights in UK for 2025',
    excerpt: 'Current updates on the Graduate Route visa and what it means for students planning to study in the United Kingdom.',
    content: 'The UK continues to offer excellent post-study work opportunities through its Graduate Route visa...',
    date: 'Feb 28, 2025',
    author: 'Legal Desk',
    category: 'Visa Updates',
    image: 'https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?q=80&w=800&auto=format&fit=crop',
    slug: 'uk-work-rights',
  },
];

export const BLOG_POSTS: BlogPost[] = Array.from({ length: 30 }).map((_, i) => {
  const original = INITIAL_BLOG_POSTS[i % INITIAL_BLOG_POSTS.length];
  const part = Math.floor(i / INITIAL_BLOG_POSTS.length);
  return {
    ...original,
    id: `${i + 1}`,
    title: part > 0 ? `${original.title} (Part ${part + 1})` : original.title,
    slug: part > 0 ? `${original.slug}-part-${part + 1}` : original.slug,
    date: `Mar ${i + 1}, 2025`,
  };
});